import Head from 'next/head'
import { FooterSection } from '../01-sections/FooterSection'
import { HeaderSection } from '../01-sections/HeaderSection'

export const MasterLayout = ({children}) => {
    return(
        <div className="app">
            <Head>
                <title>Nextflix Jobs</title>
                <meta name="Netflix Jobs" content="Generated by Ricardo Oliva Alonso" />
                <link rel="icon" href="/favicon.png" />
			</Head>

            <HeaderSection />

            {children}

            <FooterSection />
        </div>
    )
}